FROM apache/airflow:2.7.3-python3.11

USER root

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        git \
        curl \
        libpq-dev \
        python3-dev \
        libffi-dev \
        libssl-dev \
        default-libmysqlclient-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /requirements.txt

USER airflow

RUN pip install --upgrade pip
RUN pip install --no-cache-dir \
    --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.7.3/constraints-3.11.txt" \
    -r /requirements.txt

WORKDIR /opt/airflow

EXPOSE 8080

CMD ["bash"]